#include "salt/nvfp4.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static uint32_t bits_of(float value) {
    uint32_t bits;
    memcpy(&bits, &value, sizeof(bits));
    return bits;
}

static void *read_exact(const char *path, size_t nbytes) {
    FILE *handle = fopen(path, "rb");
    void *data = malloc(nbytes);
    if (!handle || !data || fread(data, 1, nbytes, handle) != nbytes ||
        fgetc(handle) != EOF) {
        fprintf(stderr, "cannot read exact NVFP4 fixture %s\n", path);
        exit(2);
    }
    fclose(handle);
    return data;
}

int main(void) {
    static const float positive[8] = {
        0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f
    };
    for (int i = 0; i < 8; i++) {
        if (salt_nvfp4_e2m1((uint8_t)i) != positive[i] ||
            salt_nvfp4_e2m1((uint8_t)(i | 8)) != -positive[i]) {
            fprintf(stderr, "E2M1 codebook mismatch at %d\n", i);
            return 1;
        }
    }
    if (salt_nvfp4_e4m3fn(0x38) != 1.0f ||
        salt_nvfp4_e4m3fn(0x68) != 64.0f ||
        salt_nvfp4_e4m3fn(0x7e) != 448.0f ||
        salt_nvfp4_e4m3fn(0xfe) != -448.0f ||
        !isnan(salt_nvfp4_e4m3fn(0x7f))) {
        fputs("E4M3FN decode mismatch\n", stderr);
        return 1;
    }
    {
        uint8_t code = 0;
        if (salt_nvfp4_e4m3fn_encode(64.0f, &code) != 0 || code != 0x68 ||
            salt_nvfp4_e4m3fn_encode(448.0f, &code) != 0 || code != 0x7e ||
            salt_nvfp4_e4m3fn_encode(-448.0f, &code) != 0 || code != 0xfe) {
            fputs("E4M3FN encode mismatch\n", stderr);
            return 1;
        }
    }
    {
        static const float input[32] = {
            -6.0f, -5.0f, -4.0f, -3.0f, -2.0f, -1.5f, -1.0f, -0.5f,
             0.0f,  0.25f, 0.5f, 0.75f, 1.0f, 2.0f, 4.0f, 6.0f,
            -3.0f, -2.5f, -2.0f, -1.5f, -1.0f, -0.5f, 0.0f, 0.25f,
             0.5f,  0.75f, 1.0f, 1.5f, 2.0f, 2.5f, 3.0f, 0.0f
        };
        static const uint8_t expected_packed[16] = {
            239, 222, 188, 154, 0, 33, 66, 118,
            239, 222, 172, 16, 50, 84, 102, 7
        };
        static const uint8_t expected_scales[2] = {104, 96};
        static const uint32_t expected_dequant_bits[32] = {
            0xc0c00000u, 0xc0800000u, 0xc0800000u, 0xc0400000u,
            0xc0000000u, 0xbfc00000u, 0xbf800000u, 0xbf000000u,
            0x00000000u, 0x00000000u, 0x3f000000u, 0x3f800000u,
            0x3f800000u, 0x40000000u, 0x40800000u, 0x40c00000u,
            0xc0400000u, 0xc0000000u, 0xc0000000u, 0xbfc00000u,
            0xbf800000u, 0xbf000000u, 0x00000000u, 0x3e800000u,
            0x3f000000u, 0x3f400000u, 0x3f800000u, 0x3fc00000u,
            0x40000000u, 0x40000000u, 0x40400000u, 0x00000000u
        };
        uint8_t packed[16], scales[2];
        float dequant[32];
        if (salt_nvfp4_quantize_input_reference(
                input, 32, 64.0f, packed, scales, dequant) != 0 ||
            memcmp(packed, expected_packed, sizeof(packed)) != 0 ||
            memcmp(scales, expected_scales, sizeof(scales)) != 0) {
            fputs("NVFP4 activation Q/DQ bytes mismatch\n", stderr);
            return 1;
        }
        for (int i = 0; i < 32; i++) {
            if (bits_of(dequant[i]) != expected_dequant_bits[i]) {
                fprintf(stderr, "NVFP4 activation dequant mismatch at %d\n", i);
                return 1;
            }
        }
        {
            uint8_t weights[32];
            uint8_t weight_scales[4] = {0x38, 0x38, 0x38, 0x38};
            uint8_t scratch_packed[16], scratch_scales[2];
            float scratch_dequant[32], scalar_output[2], simd_output[2];
            for (int i = 0; i < 16; i++) weights[i] = 0x22;
            for (int i = 16; i < 32; i++) weights[i] = 0xa2;
            salt_nvfp4_set_simd(0);
            if (salt_nvfp4_matvec_reference(
                    weights, weight_scales, 1.0f, 64.0f,
                    2, 32, input, scalar_output,
                    scratch_packed, scratch_scales, scratch_dequant) != 0 ||
                bits_of(scalar_output[0]) != 0xc0d00000u ||
                bits_of(scalar_output[1]) != 0xc0f00000u) {
                fputs("NVFP4 canonical matvec mismatch\n", stderr);
                return 1;
            }
            salt_nvfp4_set_simd(1);
            if (salt_nvfp4_matvec_reference(
                    weights, weight_scales, 1.0f, 64.0f,
                    2, 32, input, simd_output,
                    scratch_packed, scratch_scales, scratch_dequant) != 0 ||
                memcmp(scalar_output, simd_output, sizeof scalar_output) != 0) {
                fputs("NVFP4 scalar/SIMD mismatch\n", stderr);
                return 1;
            }
        }
    }

    /* Pinned real artifact slice: layer 0, expert 0, gate, R=3 C=2816.
     * The fixture was generated by the pinned vLLM/compressed-tensors stack.
     * Compare format/QDQ independently of tensor-core matmul reduction order. */
    {
        static const char root[] =
            "models/gemma4-26b-a4b/qualification/nvfp4-component";
        char path[512];
        uint8_t *weights, *weight_scales, *input_packed_want;
        uint8_t *input_scales_want, *input_packed, *input_scales;
        float *globals, *input, *input_dq_want, *weight_dq_want;
        float *input_dq, *weight_dq;
#define READ_FIXTURE(name, nbytes) \
        (snprintf(path, sizeof(path), "%s/%s", root, name), \
         read_exact(path, nbytes))
        weights = READ_FIXTURE("weight_packed.bin", 4224);
        weight_scales = READ_FIXTURE("weight_scales.bin", 528);
        globals = READ_FIXTURE("global_scales.bin", 8);
        input = READ_FIXTURE("input.bin", 11264);
        input_packed_want = READ_FIXTURE("input_packed.expected.bin", 1408);
        input_scales_want = READ_FIXTURE("input_scales.expected.bin", 176);
        input_dq_want = READ_FIXTURE("input_dequant.expected.bin", 11264);
        weight_dq_want = READ_FIXTURE("weight_dequant.runtime.expected.bin", 33792);
        input_packed = malloc(1408);
        input_scales = malloc(176);
        input_dq = malloc(11264);
        weight_dq = malloc(33792);
        if (!input_packed || !input_scales || !input_dq || !weight_dq)
            return 1;
        if (salt_nvfp4_quantize_input_reference(
                input, 2816, globals[1], input_packed, input_scales,
                input_dq) != 0 ||
            memcmp(input_packed, input_packed_want, 1408) != 0 ||
            memcmp(input_scales, input_scales_want, 176) != 0) {
            fputs("real NVFP4 input code/scale mismatch\n", stderr);
            return 1;
        }
        for (int i = 0; i < 2816; i++) {
            if (bits_of(input_dq[i]) != bits_of(input_dq_want[i]) &&
                !(input_dq[i] == 0.0f && input_dq_want[i] == 0.0f)) {
                fprintf(stderr, "real NVFP4 input Q/DQ mismatch at %d\n", i);
                return 1;
            }
        }
        if (salt_nvfp4_dequantize_weights_reference(
                weights, weight_scales, globals[0], 3, 2816,
                weight_dq) != 0 ||
            memcmp(weight_dq, weight_dq_want, 33792) != 0) {
            fputs("real NVFP4 weight dequant mismatch\n", stderr);
            return 1;
        }
        free(weights);
        free(weight_scales);
        free(globals);
        free(input);
        free(input_packed_want);
        free(input_scales_want);
        free(input_dq_want);
        free(weight_dq_want);
        free(input_packed);
        free(input_scales);
        free(input_dq);
        free(weight_dq);
#undef READ_FIXTURE
    }
    puts("PASS test_nvfp4");
    return 0;
}
